services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # smtp
      - "8025:8025" # ui

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672" # amqp
      - "15672:15672" # ui
    environment:
      TZ: Asia/Bangkok
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      TZ: Asia/Bangkok
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - mongodata:/data/db

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8089:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  rabbitmqdata:
  mongodata:
